version: '3'
services:
  server:
    image: php8
    ports:
      - "80:80"
      #      - "443:443"
      - "9001:9001"
    volumes:
      - ./project:/var/www/html/project/:rw # 项目
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf:ro
      - ./docker/nginx/config/general.conf:/etc/nginx/general.conf:ro
      - ./docker/nginx/config/conf.d:/etc/nginx/conf.d/:ro
      - ./docker/nginx/config/cert:/etc/nginx/cert/:ro # 证书
      - ./docker/nginx/supervisor.d/nginx.ini:/etc/supervisor.d/nginx.ini:ro # nginx进程
    container_name: server
    working_dir: /var/www/html/project
    networks:
      - local_network
  # 开发和测试环境加入共享网络连接redis
  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --requirepass scmmwl888 --appendonly yes
    container_name: redis
    networks:
      - local_network
networks:
  local_network:
    name: local_network