version: "3"
services:
  server:
    image: lestat220255/nginx-php:beta
    ports:
      - "80:80"
      #      - "443:443"
      - "9001:9001"
    volumes:
      - ./projects:/var/www/html/projects/:rw # 项目
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf:ro
      - ./docker/nginx/config/general.conf:/etc/nginx/general.conf:ro
      - ./docker/nginx/config/conf.d:/etc/nginx/conf.d/:ro
      - ./docker/nginx/config/cert:/etc/nginx/cert/:ro # 证书
      - ./docker/nginx/supervisor.d/nginx.ini:/etc/supervisor.d/nginx.ini:ro # nginx进程
    container_name: server
    working_dir: /var/www/html/projects
    networks:
      - local_network
  # 开发和测试环境加入共享网络连接redis
  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --requirepass 123 --appendonly yes
    container_name: redis
    networks:
      - local_network
  # mysql:
  #   image: mysql:8.0.25
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     #- MYSQL_USER=user
  #     #- MYSQL_PASSWORD=password
  #   volumes:
  #     #配置文件
  #     - ./mysql:/etc/mysql/my.cnf:ro
  #     #数据目录
  #     - ./mysql/data:/var/lib/mysql/:rw
  #     #查询日志文件
  #     #- ./logs/mysql/query_mysql.log:/var/logs/mysql/query.mysql.log:rw
  #     #慢查询日志文件
  #     #- ./logs/mysql/slow_mysql.log:/var/logs/mysql/slow.mysql.log:rw
  #   ports:
  #     - "3306:3306"
  #   container_name: mysql
  #   networks:
  #     - local_network
  rabbitmq:
    image: rabbitmq:3.8.16-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - "15672:15672"
      - "5672:5672"
    container_name: rabbitmq
    networks:
      - local_network
networks:
  local_network:
    name: local_network
